### ISSUE TITLE
Using dotnetify with react-native-desktop

### ISSUE THREAD

**Issue by writzx** [dsuryd/dotNetify#175]
While trying to use dotnetify with react-native-desktop, I keep on getting this exception.
When trying to the same dotnet project with pure react or react-native, it works as expected. I am not sure what is the error in this case since I didn't find any useful information about this error message while googling it.

```
info: Microsoft.AspNetCore.Server.Kestrel[17]
      Connection id "0HLKEENLFUL13" bad request data: "Request line too long."
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Request line too long.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeStartLine(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

I would like to know any workarounds for this problem or leads on why this is happening.

**Comment by dsuryd** [comment]
There's not much info to go on.  I never work with that library and the error was an HTTP request failure, not even dotNetify.  I suggest you find out what's being requested and compare it with the one that works.

**Comment by writzx** [comment]
The reason that I am confused about this is the lack of info on the actual error message. The setup I have right now is basically a mixture of HelloWorld from both the library templates and that does not work. I'm not sure if there is any http call going on in the background.


As a workaround I am using electron for now, but I would like to switch to react-native-desktop if at all possible.

(I also posted on their forums to check if they have any leads on this but nothing so far.)

**Comment by writzx** [comment]
Turns out the error was due to a second server that needed to be run to run react-native-desktop. That server was using the port 5000 and ASP.net server overrides it when it starts and thats why the error was "Request line too long."

However I am still not able to get it working correctly but I believe thats a completely different issue.
