### ISSUE TITLE
How to catch ViewModel backend exceptions

### ISSUE THREAD

**Issue by samartzidis** [dsuryd/dotNetify#228]
Hi,

Thanks for this impressive library. 

I am trying to catch exceptions at the JavaScript side thrown at the C# ViewModel backend but with no success. 

These are the relevant code fragments from my current setup:

React JS component:
```
constructor(props) {
    super(props);   
    this.vm = dotnetify.react.connect('ConfigVm', this, { exceptionHandler: ex => this.onException(ex) });
    this.dispatch = state => this.vm.$dispatch(state);
  }
  onException(ex) {
    alert("Exception!"); // This never gets called
  }
const onClickButton = () => {
      this.dispatch({ Dummy: {  } });  // This gets invoked from JS
  };
```

C# ViewModel backend:
```
// This gets called at C#
public Action<DummyData> Dummy => data =>
{
    throw new ApplicationException("Test"); // C# throw exception
}
```

What happens when the ApplicationException is thrown is that the application crashes:
```
Process terminated. Assertion Failed
System.ApplicationException: Test
   at ReactTest.ViewModelsMyVm.<get_Dummy>b__20_0(MyVmDummyData data) in C:\xxx\MyVm.cs:line 39
   at DotNetify.Command`1.Execute(Object parameter)
   at DotNetify.VMSerializer.Deserialize(Object viewModel, String vmPath, String newValue)
   at DotNetify.VMSerializer.Deserialize(Object viewModel, String vmPath, String newValue)
   at DotNetify.BaseVM.Deserialize(Object instance, String propertyPath, String newValue)
```

How am I supposed to gracefully catch exceptions thrown from the C# backend?

Thank you!

**Comment by dsuryd** [comment]
Strange, the process shouldn't have terminated since there's a try-catch block down the stack.  I ran some experiments; the crash was reproducible when using `dotnet run` command line targetting `netcore3.0`.   It didnt crash when it's run from VS 2019, or if the target's dowgraded to `netcore2.2`.  Could you confirm this?

**Comment by samartzidis** [comment]
Hi. Thanks for the quick answer.

I tested by directly spawning the project in VS2019 and also via "dotnet run" in the console. I tried both with netcoreapp3.0 and netcoreapp3.1. I am using DotNetify.SignalR 3.5.0. In all cases when the C# backend throws the application exception the dot net runtime crashes with a "Process terminated. Assertion Failed" and then the rest of the stacktrace that I put in my original message. I could not downgrade to netcoreapp2.0 due to other library dependencies.

If it helps, this is my Startup and Program classes:

```
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddLogging(loggingBuilder =>
            {
                loggingBuilder.AddConfiguration(Configuration.GetSection("Logging"));
                loggingBuilder.AddConsole();
                loggingBuilder.AddDebug();
            });

            services.AddControllersWithViews();

            // In production, the React files will be served from this directory
            services.AddSpaStaticFiles(configuration =>
            {
                configuration.RootPath = "ClientApp/build";
            });

            services.AddMemoryCache();
            services.AddSignalR();
            services.AddDotNetify();

            services.AddSingleton<IConfiguration>(t => Configuration);

            //services.AddLogging(configure => configure.AddConsole());

            // Auto Mapper Configurations
            var mappingConfig = new MapperConfiguration(mc =>
            {
                mc.AddProfile(new MappingProfile());
            });
            services.AddSingleton(mappingConfig.CreateMapper());
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseWebSockets();
            app.UseDotNetify();

            //app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseSpaStaticFiles();

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller}/{action=Index}/{id?}");

                endpoints.MapHub<DotNetifyHub>("/dotnetify");
            });

            app.UseSpa(spa =>
            {
                spa.Options.SourcePath = "ClientApp";

                if (env.IsDevelopment())
                {
                    spa.UseReactDevelopmentServer(npmScript: "start");
                }
            });
        }
    }
public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }
```

Thanks.

**Comment by samartzidis** [comment]
After some analysis, I do not think that this has something to do with neither your library nor my code. It seems that netcore3.* has a different implementation of the **DefaultTraceListener** class than netcore 2.*.

Specifically, the invocation of DefaultTraceListener.Fail() in netcore3.* invokes Environment.FailFast(), but only when the application is running without a debugger attached, which in turn aborts the CLR process. Weirdly, netcore 2.* does not do that. 

You use Trace.Fail() in various places within your code (where you catch exceptions) including the affected part where you mention that you do catch the exception (DotNetifyLib.Core\BaseVM\VMSerializer.cs:156):
```
         catch (Exception ex)
         {
            Trace.Fail(ex.ToString());
            throw ex;
         }
```
Unfortunately the DefaultTraceListener.Fail() has the afforementioned consequence.

My current workaround is to do this at my application startup:
```
Trace.Listeners.Clear();
Trace.Listeners.Add(new ConsoleTraceListener());
```
With this everything works fine with my initially submitted code, that is I can get the exception at the JS side through the registered exceptionHandler.

**Comment by dsuryd** [comment]
Thank you for the analysis.  I'll plan to move away from using Trace.
