### ISSUE TITLE
Cannot run app after upgrade to VS2017 15.3.3

### ISSUE THREAD

**Issue by JarrodJ83** [dsuryd/dotNetify#41]
After upgrading VS2017 to the latest build I get the following when trying to run npm start:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\jarrod.johnson\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v6.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle myapp.portal.dotnetify@0.1.1~prestart: myapp.portal.dotnetify@0.1.1
6 info lifecycle myapp.portal.dotnetify@0.1.1~start: myapp.portal.dotnetify@0.1.1
7 verbose lifecycle myapp.portal.dotnetify@0.1.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle myapp.portal.dotnetify@0.1.1~start: PATH: C:\Users\jarrod.johnson\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\github\jarrodj83\myapp.Portal\myapp.portal.dotnetify\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.3;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.3;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\\MSBuild\15.0\bin;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\DEMRJBIE.MOU\lib\win32\x86;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Shoreline Communications\ShoreWare Client\;C:\Program Files (x86)\Shoreline Communications\ShoreWare Client\win64;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files\TortoiseSVN\bin;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files\Seq\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Ruby24-x64\bin;C:\Users\jarrod.johnson\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\jarrod.johnson\AppData\Local\atom\bin;C:\Program Files (x86)\Xming;C:\Program Files (x86)\Xming;C:\Users\jarrod.johnson\AppData\Roaming\npm;C:\Users\jarrod.johnson\AppData\Local\Programs\Fiddler;C:\Users\jarrod.johnson\.nuget\packages\newtonsoft.json\10.0.1\tools;C:\Users\jarrod.johnson\.nuget\packages\microsoft.codeanalysis.analyzers\1.1.0\tools;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.entityframeworkcore.tools\2.0.0\tools;C:\Users\jarrod.johnson\.nuget\packages\newtonsoft.json\10.0.2\tools;C:\Users\jarrod.johnson\.nuget\packages\newtonsoft.json\10.0.3\tools;C:\Users\jarrod.johnson\.nuget\packages\autofixture\3.50.6\tools
9 verbose lifecycle myapp.portal.dotnetify@0.1.1~start: CWD: C:\github\jarrodj83\myapp.Portal\myapp.portal.dotnetify
10 silly lifecycle myapp.portal.dotnetify@0.1.1~start: Args: [ '/d /s /c',
10 silly lifecycle   'concurrently "react-scripts start" "dotnet watch run" --kill-others' ]
11 silly lifecycle myapp.portal.dotnetify@0.1.1~start: Returned: code: 1  signal: null
12 info lifecycle myapp.portal.dotnetify@0.1.1~start: Failed to exec start script
13 verbose stack Error: myapp.portal.dotnetify@0.1.1 start: `concurrently "react-scripts start" "dotnet watch run" --kill-others`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\jarrod.johnson\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\jarrod.johnson\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid myapp.portal.dotnetify@0.1.1
15 verbose cwd C:\github\jarrodj83\myapp.Portal\myapp.portal.dotnetify
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jarrod.johnson\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v6.11.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error myapp.portal.dotnetify@0.1.1 start: `concurrently "react-scripts start" "dotnet watch run" --kill-others`
22 error Exit status 1
23 error Failed at the myapp.portal.dotnetify@0.1.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Does anything stand out here to you that might be causing this issue?

**Comment by dsuryd** [comment]
Not particularly. Try dotnet restore and dotnet build first before npm start.

**Comment by JarrodJ83** [comment]
Seems like a reboot was all it took. Not sure why though.

**Comment by dsuryd** [comment]
Cool. I am closing the issue.
