### ISSUE TITLE
Deploy issues on Ubuntu 16.04.2 LTS (xenial)

### ISSUE THREAD

**Issue by tw-bert** [dsuryd/dotNetify#44]
Using: ` Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-77-generic x86_64)`
dotNetity: wget of master.zip as of today.

After succesfully testing dotNetify on a Linux vagrant VM (Ubuntu 16.04.02), I am trying to start the `WebApplication.Core.React` example on an existing Ubuntu server on our LAN. 

First problem I ran into, is that only the 2.0.0 dotnet core framework was present on that machine.

```bash
tw@srv-nondisclosed-02:~/PublishOutput$ dotnet exec WebApplication.Core.React.dll
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.4' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.0.4'.
```
I solved it for now by `apt install dotnet-dev-1.0.4` (after failed attempts to reconfigure the packages to 2.0.0, I got stuck on a `Could not load file or assembly 'System.Threading, Version=4.1.0.0'`, so decided to use 1.0.4 for the time being).

To your example I added one line to the WebHostBuilder: `.UseUrls("http://0.0.0.0:5000")` , so I can browse to it from windows. That gave a 500.

Then I added `app.UseDeveloperExceptionPage();` to the config. This shows (from a browser) the following exception is causing the fail:

```bash
System.InvalidOperationException: Cannot return null from an action method with a return type of 'Microsoft.AspNetCore.Mvc.IActionResult'.
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
```

Since the machine should be the same as my vagrant VM, this surprises me. 

`apt list --installed | grep dotnet` shows on both machines:

```
dotnet-dev-1.0.4/xenial,now 1.0.4-1 amd64 [installed]
dotnet-host/xenial,now 2.0.0-preview2-25407-01-1 amd64 [installed,automatic]
dotnet-hostfxr-1.0.1/xenial,now 1.0.1-1 amd64 [installed,automatic]
dotnet-hostfxr-1.1.0/xenial,now 1.1.0-1 amd64 [installed,automatic]
dotnet-hostfxr-2.0.0/xenial,now 2.0.0-1 amd64 [installed,automatic]
dotnet-runtime-2.0.0/xenial,now 2.0.0-1 amd64 [installed,automatic]
dotnet-sdk-2.0.0/xenial,now 2.0.0-1 amd64 [installed]
dotnet-sharedframework-microsoft.netcore.app-1.0.5/xenial,now 1.0.5-1 amd64 [installed,automatic]
dotnet-sharedframework-microsoft.netcore.app-1.1.2/xenial,now 1.1.2-1 amd64 [installed,automatic]
```

Any clue?

**Comment by dsuryd** [comment]
I recommend to start small, use [this HelloWorld step-by-step](http://dotnetify.net/react/from-scratch-cli) to spot compatibility problem.  It has no ASP.Net Core MVC dependency, and should run on .net core 2.0.

**Comment by tw-bert** [comment]
The HelloWorld example runs fine, except after Ctrl+C (and having browsed to it and closed the browser), I get:

```bash
Unhandled Exception: System.NotSupportedException: Collection was of a fixed size.
   at System.ThrowHelper.ThrowNotSupportedException(ExceptionResource resource)
   at System.SZArrayHelper.Remove[T](T value)
   at Microsoft.AspNetCore.SignalR.Messaging.Subscription.RemoveEvent(String key)
   at Microsoft.AspNetCore.SignalR.Messaging.DefaultSubscription.RemoveEvent(String eventKey)
   at Microsoft.AspNetCore.SignalR.Messaging.MessageBus.RemoveEvent(ISubscriber subscriber, String eventKey)
   at Microsoft.AspNetCore.SignalR.Messaging.MessageBus.DisposeSubscription(Object state)
   at Microsoft.AspNetCore.SignalR.Messaging.MessageBus.<.ctor>b__20_1(Object o)
   at Microsoft.AspNetCore.SignalR.Infrastructure.DisposableAction.Dispose(Boolean disposing)
   at Microsoft.AspNetCore.SignalR.Infrastructure.DisposableAction.Dispose()
   at Microsoft.AspNetCore.SignalR.Infrastructure.AckSubscriber.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at HelloWorldApp.Program.Main(String[] args) in /home/tw/HelloWorldApp/Program.cs:line 17
```

> [dsuryd] It has no ASP.Net Core MVC dependency, and should run on .net core 2.0.

So ASP.Net Core MVC on .net core 2.0 is not supported by dotNetify? Or do you suspect a wrong package somewhere? Please advise me on next steps.

**Comment by tw-bert** [comment]
I upgraded `DotNetifyLib.SignalR` and `WebApplication.Core.React` to dotnet 2.0. I still get the exception as before: `Cannot return null from an action method with a return type of 'Microsoft.AspNetCore.Mvc.IActionResult'`.

Maybe helpful for other problems, here are the .cs files with the latest packages:

`DotNetifyLib.SignalR.csproj`
 
```xml

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VersionPrefix>2.0.0</VersionPrefix>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>DotNetifyLib.SignalR</AssemblyName>
    <PackageId>DotNetify.SignalR</PackageId>
    <NetStandardImplicitPackageVersion>2.0.0</NetStandardImplicitPackageVersion>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <Version>2.2.1-pre</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Dicky Suryadi</Authors>
    <Description>Simple, lightweight, yet powerful way to build real-time web apps. SignalR hub for ASP.NET Core.</Description>
    <Copyright>Copyright 2015-</Copyright>
    <PackageLicenseUrl>https://github.com/dsuryd/dotNetify/blob/master/LICENSE.md</PackageLicenseUrl>
    <PackageProjectUrl>http://dotnetify.net/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/dsuryd/dotNetify</RepositoryUrl>
    <PackageTags>netcore realtime signalr mobile web websocket</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DotNetifyLib.Core\DotNetifyLib.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Gray.Microsoft.AspNetCore.SignalR.Server" Version="0.2.0-alpha1" />
    <PackageReference Include="Microsoft.AspNetCore.WebSockets" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.1.4" />
  </ItemGroup>
</Project>
```


`DotNetifyLib.Core.csproj`
 
```xml

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VersionPrefix>2.0.0</VersionPrefix>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>DotNetifyLib.Core</AssemblyName>
    <PackageId>DotNetify.Core</PackageId>
    <NetStandardImplicitPackageVersion>2.0.0</NetStandardImplicitPackageVersion>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <Version>2.2.1-pre</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Description>Simple, lightweight, yet powerful way to build real-time web apps. Library for .NET Core.</Description>
    <Authors>Dicky Suryadi</Authors>
    <PackageProjectUrl>http://dotnetify.net/</PackageProjectUrl>
    <PackageLicenseUrl>https://github.com/dsuryd/dotNetify/blob/master/LICENSE.md</PackageLicenseUrl>
    <Copyright>Copyright 2015-</Copyright>
    <RepositoryUrl>https://github.com/dsuryd/dotNetify</RepositoryUrl>
    <PackageTags>netcore realtime signalr mobile web websocket</PackageTags>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="2.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="System.ComponentModel" Version="4.3.0" />
    <PackageReference Include="System.ComponentModel.TypeConverter" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.TraceSource" Version="4.3.0" />
    <PackageReference Include="System.Security.Claims" Version="4.3.0" />
  </ItemGroup>
</Project>
```

`WebApplication.Core.React.csproj`
 
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>WebApplication.Core.React</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>WebApplication.Core.React</PackageId>
    <RuntimeFrameworkVersion>2.0.0</RuntimeFrameworkVersion>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\AFITop100.json" />
    <EmbeddedResource Include="Resources\employees.json" />
    <EmbeddedResource Include="Resources\webstore.json" />
    <EmbeddedResource Include="wwwroot\js\BookStore.js" />
    <EmbeddedResource Include="wwwroot\js\BookStore.min.js" />
    <EmbeddedResource Include="wwwroot\js\CompositeView.js" />
    <EmbeddedResource Include="wwwroot\js\CompositeView.min.js" />
    <EmbeddedResource Include="wwwroot\js\ControlTypes.js" />
    <EmbeddedResource Include="wwwroot\js\ControlTypes.min.js" />
    <EmbeddedResource Include="wwwroot\js\GridView.js" />
    <EmbeddedResource Include="wwwroot\js\GridView.min.js" />
    <EmbeddedResource Include="wwwroot\js\HelloWorld.js" />
    <EmbeddedResource Include="wwwroot\js\HelloWorld.min.js" />
    <EmbeddedResource Include="wwwroot\js\index.js" />
    <EmbeddedResource Include="wwwroot\js\index.min.js" />
    <EmbeddedResource Include="wwwroot\js\LiveChart.js" />
    <EmbeddedResource Include="wwwroot\js\LiveChart.min.js" />
    <EmbeddedResource Include="wwwroot\js\PaginatedTable.js" />
    <EmbeddedResource Include="wwwroot\js\PaginatedTable.min.js" />
    <EmbeddedResource Include="wwwroot\js\SimpleList.js" />
    <EmbeddedResource Include="wwwroot\js\SimpleList.min.js" />
    <None Update="wwwroot\**\*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DotNetifyLib.SignalR\DotNetifyLib.SignalR.csproj" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.1.4" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.0.7.9" />
  </ItemGroup>
</Project>
```

They build fine, and *are* working on one Ubuntu Xenial (a vagrant VM), but not on another Ubuntu Xenial (an existing server on our LAN).

**Comment by tw-bert** [comment]
Found some more info. Running with remote debugging (SSL), I could see the following exception:

```
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
/home/tw/dotNetify-master/WebApplication.Core.React/wwwroot/index.html not found
```

So I did `mv Index.html index.html` . After that, I did not get a 500 anymore, but instead got an almost empty page:

![dotnetify empty](https://user-images.githubusercontent.com/3413888/30429403-9f1a59d6-9957-11e7-90ed-8fa1055cc819.png)

Note that on the vagrant Ubuntu VM, the rename was not needed, and Index.html worked fine.
Again, any clue?

**Comment by dsuryd** [comment]
Since HelloWorld example is working, this looks more of an issue between the demo examples implementation and this particular Ubuntu environment.  You found one problem with file name case sensitivity, there's probably more along the same line.  For the particular error above, it was trying to access an MVC controller route (HomeController.cs) but failed.  Nothing to do with core dotNetify yet.  Type in directly the path into the browser: http://.../module/get/Index/IndexVM and find out why it's giving you 500 error instead of the expected javascript content.

**Comment by tw-bert** [comment]
Yes, after doing:

```bash
mv wwwroot/js/index.js wwwroot/js/Index.js
```

It works fine.

Puzzled why this behaviour regarding case sensitivity is different on that particular Ubuntu Xenial server. I checked `LANG` , `LC_COLLATE` and `LC_ALL` environment variables, which is the same on both machines (only `LANG=en_US.UTF-8`).

I'll investigate a bit more, but it clearly has nothing to do with dotnetify. More likely, how Kestrel handles environment settings or other server configuration settings and/or the file system. I'll close this issue when I have nothing more to add.

What did help, is that remote debugging from VS2017 to a dotnet core process on Ubuntu via SSL works flawlessly.

Thank you for your help.

**Comment by dsuryd** [comment]
Awesome summary! Now that SignalR core 2.0 alpha is out, will look into porting in the upcoming weeks.

**Comment by tw-bert** [comment]
You're welcome! Looking forward to the 2.0 port.

**Comment by tw-bert** [comment]
Hi Dicky, small heads up: You renamed index.jsx/index.js/index.min.js to Index.jsx/Index.js/Index.min.js , but you missed one spot: inside https://github.com/dsuryd/dotNetify/blob/master/WebApplication.Core.React/compilerconfig.json the filenames are still lower case.

Thanks for the changes, cheers TW

**Comment by tw-bert** [comment]
Hi Dicky, I'm following your port to `netstandard2.0` with great interest. I just tested it, but I feel that you might not be finished yet (I didn't get a running React demo). It would be great to see a readme with the current status. Good luck with the port!

**Comment by dsuryd** [comment]
I'm close to releasing, just need to work out a few last issues and update the doc.  Thank you for letting me know the problem with the React demo.  Everything should've been working, but apparently the bundle file wasn't updated before.  If you pull fresh now, you should be able to get it running.

**Comment by tw-bert** [comment]
Now the basics work, awesome!

I have a couple of remarks:

1. From the command line, it seems you need to strip some deprecated csproj stuff. It *does* build from VS2017, but not from `dotnet` command line.
```bash
dotnet restore
DotNetifyLib.Core.csproj : error NU1003: PackageTargetFallback and AssetTargetFallback cannot be used together. Remove PackageTargetFallback(deprecated) references from the project environment. [WebApplication.React.csproj]
```

2. The performace isn't good. `netcoreapp1.0` showed the hello world example in 2 seconds, `netcoreapp2.0` 11 seconds. (F5 from VS)

3. If I run it from VS, not IIS (but simply Kestrel), I get: `Unhandled exception at line 32, column 7 in http://localhost:5000/lib/dotnetify-react.js 0x800a1391 - JavaScript runtime error: 'dotnetifyHub' is undefined`

4. Build fails on Ubuntu, because xcopy is not unix, and backward slashes are used, and IDE specific environment settings are used. I solved it by:
```
<Exec Command="cp -rp  &quot;../../src/react/&quot;*.js &quot;./wwwroot/lib&quot;&#xD;&#xA;cp -rp &quot;../../src/&quot;*.js &quot;./wwwroot/lib&quot;" />
```

I couldn't test it properly on Kestrel (Ubuntu/Windows) because it most probably hits the same exception as (3). Therefore I couldn't verify if the `Collection was of a fixed size.` is fixed in this version of SignalR.

Thanks for your project, TW

**Comment by dsuryd** [comment]
I think the latest will resolve every issue you mentioned above.  Let me know how it goes. Thx!

**Comment by tw-bert** [comment]
The performance issue is solved, great!
The build and deploy mishaps aren't 100% okay I'm afraid.
On windows, after a clean repo pull and then `dotnet run` in `WebApplication.React` results in a running site with only the static content being shown. F12 console shows jquery not found.
On ubuntu, I could not get it working with `dotnet run`, but only when doing `dotnet build`, then `cp -rp "../../src/react/"*.js "./wwwroot/lib" && cp -rp "../../src/"*.js "./wwwroot/lib"` and then `dotnet exec bin/Debug/netcoreapp2.0/WebApplication.React.dll` .
Still great to see it working already ;)

**Comment by dsuryd** [comment]
The .net core 2.0 port is released.  I've tested the `WebApplication.React` repo on both windows/IE and macOS Sierra/Safari with `dotnet run`.  All worked without a hitch. I fully expect your Ubuntu test will be the same :).

**Comment by tw-bert** [comment]
I can confirm: Works without a hitch. Great stuff.
